title: Shervin Khazaeli # your name (or website title) here
logo: "/images/logo.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <h2>Shervin Khazaeli</h2>
  Ph.D. | Civil Engineering<br>
  &nbsp;&nbsp;&nbsp;| Artifitial Intelligence
  <br><br>
  <b>Applications:</b> smart monitoring; decision making; AI governance
  <br><br>
  <b>Organizations</b>
  <br>
  <b>[2023-]</b> Project Management Institute <br>
  <b>[2017-]</b> Smart City X
  <br><br>
  <b> Activities </b>
  <br>
  <b>[2022-]</b> Senior Data Scientist <br>
  <b>[2020-]</b> Instrucor <br>
  <b>[2017-]</b> Co-Founder (Smart City X) <br>
  <b>[2014-2022]</b> Research Assistant & Data Analytics Developer
  <br><br>
  <a href = "mailto: shervin.khazaeli@gmail.com">Email</a> | 
  <a href="https://scholar.google.com/citations?hl=en&user=2_GdC3kAAAAJ&view_op=list_works&sortby=pubdate">Scholar</a> |   
  <a href="https://www.linkedin.com/in/shervinkh/">LinkedIn</a> |   
  <a href="https://github.com/moderncan">Github</a> |   
  <a href="/pdf/ShervinKhazaeliCV.pdf">CV</a> 
theme: jekyll-theme-minimal
#google_analytics: UA-216599147-1 # your Google Analytics tracking ID here
#  <b>[2023-]</b> <a href="https://www.credly.com/badges/e7715e9e-784f-4079-ac4c-53a56961bd3f/linked_in_profile"> Machine Learning Engineer</a> <br>
